Queima.Web.App/src/Queima.Web.App/Controllers/ArtistasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Queima.Web.App.DAL;
using Queima.Web.App.Models;
using Queima.Web.App.Interfaces;
using Queima.Web.App.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Net.Http.Headers;
using System.IO;
using Queima.Web.App.Helpers;
using ImageProcessorCore;

namespace Queima.Web.App.Controllers
{
    public class ArtistasController : Controller
    {
        public IGenericRepository<Artista> _repository;
        private IHostingEnvironment _env;

        public ArtistasController(IGenericRepository<Artista> repository, IHostingEnvironment env)
        {
            _repository = repository;
            _env = env;
        }

        // GET: Artistas
        public async Task<IActionResult> Index()
        {
            IEnumerable<Artista> lista = await _repository.FindAll();
            var lista_vm = new List<ArtistaViewModel>();

            foreach (Artista a in lista)
            {
                var vm = new ArtistaViewModel(a);
                lista_vm.Add(vm);
            }
            return View(lista_vm);
        }

        // GET: Artistas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artista = await _repository.Get(id.Value);
            if (artista == null)
            {
                return NotFound();
            }
            ArtistaViewModel vm = new ArtistaViewModel(artista);
            ViewBag.FilePath = vm.ImagemPath;
            ViewBag.Alt = vm.Nome;
            return View(vm);
        }

        // GET: Artistas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Artistas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Biografia,DataAtuacao,FacebookUrl,Nome,Palco,SpotifyUrl,TwitterUrl,FilePath")] ArtistaViewModel vm, IFormFile Imagem)
        {
            Artista new_artista = new Artista();
            if (ModelState.IsValid && Imagem != null && Imagem.Length > 0 && FilesHelper.VerifyFileSize(Imagem) && FilesHelper.VerifyFileExtension(Imagem.FileName))
            {
                var upload = Path.Combine(_env.WebRootPath, "imagens", "artistas");

                // guardar imagem
                using (var fileStream = new FileStream(Path.Combine(upload, Imagem.FileName), FileMode.Create))
                {
                    await Imagem.CopyToAsync(fileStream);
                }
                // guardar imagem thumbnail
                var thumbnail = Path.GetFileNameWithoutExtension(Path.Combine(upload, Imagem.FileName));
                thumbnail += "_tb";
                using (var stream = new FileStream(Path.Combine(upload, Imagem.FileName), FileMode.Open))
                using (var output = new FileStream(Path.Combine(upload, thumbnail + ".jpg"), FileMode.OpenOrCreate))
                {
                    Image image = new Image(stream);
                    image.Resize(image.Width / 2, image.Height / 2)
                         .Save(output);
                }

                new_artista.Nome = vm.Nome;
                new_artista.Biografia = vm.Biografia;
                new_artista.DataAtuacao = DateTime.Parse(vm.DataAtuacao);
                new_artista.FacebookUrl = vm.FacebookUrl;
                new_artista.TwitterUrl = vm.TwitterUrl;
                new_artista.SpotifyUrl = vm.SpotifyUrl;
                new_artista.Palco = vm.Palco;
                new_artista.ImagemPath = "\\imagens\\artistas\\" + Imagem.FileName;
                new_artista.ImagemUrl = HttpContext.Request.Host.Host + "/imagens/artistas/" + Imagem.FileName;
                await _repository.Save(new_artista);

                return RedirectToAction("Index");
            }
            return View(vm);
        }

        // GET: Artistas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artista = await _repository.Get(id.Value);
            if (artista == null)
            {
                return NotFound();
            }

            var vm = new ArtistaViewModel(artista);

            return View(vm);
        }

        // POST: Artistas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Biografia,DataAtuacao,FacebookUrl,Nome,Palco,SpotifyUrl,TwitterUrl,ImagemPath,ImagemUrl")] ArtistaViewModel vm, IFormFile Imagem)
        {
            if (id != vm.Id)
            {
                return NotFound();
            }
            Artista artista = await _repository.Get(id);
            if (ModelState.IsValid)
            {
                try
                {
                    // editar imagem
                    if (Imagem != null && Imagem.Length > 0 && FilesHelper.VerifyFileSize(Imagem) && FilesHelper.VerifyFileExtension(Imagem.FileName))
                    {
                        var upload = Path.Combine(_env.WebRootPath, "imagens", "artistas");

                        // guardar imagem tamanho normal
                        using (var fileStream = new FileStream(Path.Combine(upload, Imagem.FileName), FileMode.Create))
                        {
                            await Imagem.CopyToAsync(fileStream);
                        }
                        // guardar imagem thumbnail
                        var thumbnail = Path.GetFileNameWithoutExtension(Path.Combine(upload, Imagem.FileName));
                        thumbnail += "_tb";
                        using (var stream = new FileStream(Path.Combine(upload, Imagem.FileName), FileMode.Open))
                        using (var output = new FileStream(Path.Combine(upload, thumbnail + ".jpg"), FileMode.OpenOrCreate))
                        {
                            Image image = new Image(stream);
                            image.Resize(image.Width / 2, image.Height / 2)
                                 .Save(output);
                        }

                        // apagar imagem antiga
                        var path = _env.WebRootPath + vm.ImagemPath;
                        var tb_path = _env.WebRootPath + "\\imagens\\artistas\\" + Path.GetFileNameWithoutExtension(artista.ImagemPath);
                        tb_path += "_tb.jpg";
                        if (System.IO.File.Exists(path) && System.IO.File.Exists(tb_path))
                        {
                            System.IO.File.Delete(path);
                            System.IO.File.Delete(tb_path);
                        }
                        artista.ImagemPath = "\\imagens\\artistas\\" + Imagem.FileName;
                        artista.ImagemUrl = HttpContext.Request.ToString() + "/imagens/artistas/" + Imagem.FileName;
                    }

                    artista.Nome = vm.Nome;
                    artista.Biografia = vm.Biografia;
                    artista.DataAtuacao = DateTime.Parse(vm.DataAtuacao);
                    artista.FacebookUrl = vm.FacebookUrl;
                    artista.TwitterUrl = vm.TwitterUrl;
                    artista.SpotifyUrl = vm.SpotifyUrl;
                    artista.Palco = vm.Palco;

                    await _repository.Update(artista);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtistaExists(artista.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(vm);
        }

        // GET: Artistas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artista = await _repository.Get(id.Value);
            if (artista == null)
            {
                return NotFound();
            }
            var vm = new ArtistaViewModel(artista);

            return View(vm);
        }

        // POST: Artistas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artista = await _repository.Get(id);
            var path = _env.WebRootPath + artista.ImagemPath;
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            await _repository.Delete(artista);

            return RedirectToAction("Index");
        }

        private bool ArtistaExists(int id)
        {
            if (_repository.Get(id) != null)
            {
                return true;
            }
            return false;
        }
    }
}

Queima.Web.App/src/Queima.Web.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Queima das Fitas Backoffice</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Queima das Fitas Backoffice</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="LocalAtividadesAcademicas" asp-action="Index">Pontos de Interesse</a></li>
                    <li><a asp-area="" asp-controller="AtividadesAcademicas" asp-action="Index">Atividades Académicas</a></li>
                    <li><a asp-area="" asp-controller="Artistas" asp-action="Index">Artistas</a></li>
                    <li><a asp-area="" asp-controller="Concursos" asp-action="Index">Concursos</a></li>
                    <li><a asp-area="" asp-controller="Transportes" asp-action="Index">Transportes</a></li>
                    <li><a asp-area="" asp-controller="MediaEdicoes" asp-action="Index">Álbuns e Fotos</a></li>
                    <li><a asp-area="" asp-controller="Bilheteira" asp-action="Index">Bilheteira</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Queima das Fitas Backoffice</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>